/* generated by unplugin-react-components */
export {}
declare global{
	const App: typeof import('./src/App')['default']
	const SapiLayout: typeof import('./src/components/layout')['SapiLayout']
	const SapiSide: typeof import('./src/components/side')['SapiSide']
	const About: typeof import('./src/views/about')['default']
	const Game: typeof import('./src/views/game')['default']
	const Home: typeof import('./src/views/home')['default']
	const NotFound: typeof import('./src/views/NotFound')['default']
	const Search: typeof import('./src/views/search')['default']
}